# Generated by Django 6.0.6 on 2026-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
