# Generated by Django 6.0.6 on 2026-06-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
    ]
